# Generated by Django 4.2.7 on 2023-11-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('client', models.CharField(max_length=100, verbose_name='Заказчик')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('server', models.CharField(blank=True, max_length=100, verbose_name='Сервер')),
                ('is_server_mine', models.BooleanField(verbose_name='На моём сервере')),
                ('rent', models.IntegerField(blank=True, verbose_name='Стоимость аренды сервера')),
                ('rent_next_payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата следующей оплаты сервера')),
                ('support', models.BooleanField(default=False, verbose_name='Поддержка')),
                ('support_price', models.IntegerField(blank=True, verbose_name='Цена поддержки')),
                ('support_next_payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата следующей оплаты поддержки')),
                ('project_price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, max_length=10000, verbose_name='Комментарий')),
                ('income', models.IntegerField(blank=True, verbose_name='Заплачено')),
                ('debt', models.IntegerField(blank=True, verbose_name='Долг')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, max_length=10000, verbose_name='Комментарий')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('payment_date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profit.project')),
            ],
            options={
                'verbose_name': 'Поддержка Приход',
                'verbose_name_plural': 'Поддержка Приход',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, max_length=10000, verbose_name='Комментарий')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('payment_date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profit.project')),
            ],
            options={
                'verbose_name': 'Доп Приход',
                'verbose_name_plural': 'Доп Приход',
                'ordering': ['-payment_date'],
            },
        ),
    ]
