# Generated by Django 4.2.7 on 2023-12-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rent',
            new_name='rent_price',
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rent_next_payment_date',
            field=models.DateField(verbose_name='Дата следующей оплаты сервера'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='support_next_payment_date',
            field=models.DateField(verbose_name='Дата следующей оплаты поддержки'),
        ),
    ]
