# Generated by Django 4.2.7 on 2023-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0002_rename_rent_project_rent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
