# Generated by Django 4.2.7 on 2023-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0004_alter_project_rent_price_alter_project_support_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='server_info',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Данные сервера'),
        ),
    ]
