# Generated by Django 4.2.7 on 2023-12-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0006_alter_project_is_server_mine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='debt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Долг'),
        ),
    ]
