# Generated by Django 4.2.7 on 2023-12-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0007_alter_project_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpayments',
            name='payment_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='supportpayments',
            name='payment_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
    ]
