# Generated by Django 4.2.7 on 2023-12-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0009_alter_additionalpayments_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
    ]
