# Generated by Django 5.0.1 on 2024-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0010_alter_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('web', 'web'), ('bot', 'bot'), ('desktop', 'desktop')], max_length=300, verbose_name='Тип Проекта')),
                ('name', models.CharField(max_length=300, verbose_name='Название проекта  ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата начала работ')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Проект портфолио',
                'verbose_name_plural': 'Проекты портфолио',
            },
        ),
    ]
