# Generated by Django 5.0.1 on 2024-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_message', models.TextField(max_length=1000, verbose_name='Сообщение для автоответчика')),
                ('common_message', models.TextField(max_length=1000, verbose_name='Сообщение для рассылки')),
                ('auto_reply_delay', models.IntegerField(default=0, verbose_name='Задержка для автоответчика')),
                ('common_message_delay', models.IntegerField(default=0, verbose_name='Задержка между сообщениями')),
                ('api_id', models.IntegerField(default=0, verbose_name='api id')),
                ('api_hash', models.CharField(max_length=150, verbose_name='api hash')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('session', models.CharField(blank=True, max_length=150, null=True, verbose_name='Session File')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='TgChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('link', models.CharField(max_length=300, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Телеграм Канал',
                'verbose_name_plural': 'Телеграм Каналы',
            },
        ),
        migrations.CreateModel(
            name='TgChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('link', models.CharField(max_length=300, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Телеграм Группа',
                'verbose_name_plural': 'Телеграм Группы',
            },
        ),
    ]
