# Generated by Django 5.0.1 on 2024-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_job_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='session',
            field=models.FileField(blank=True, max_length=1500, null=True, upload_to='', verbose_name='Session File'),
        ),
    ]
