# Generated by Django 5.0.1 on 2024-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_job_finder', '0002_alter_settings_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedWord1Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово 1 уровня',
                'verbose_name_plural': 'Ключевые слова 1 уровня',
            },
        ),
        migrations.CreateModel(
            name='AllowedWord2Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово 2 уровня',
                'verbose_name_plural': 'Ключевые слова 2 уровня',
            },
        ),
        migrations.CreateModel(
            name='DisallowedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Запрещенное слово',
                'verbose_name_plural': 'Запрещенные слова',
            },
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
