# Generated by Django 5.0.1 on 2024-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_job_finder', '0003_allowedword1level_allowedword2level_disallowedword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Слово для исключения',
                'verbose_name_plural': 'Слова для исключения',
            },
        ),
    ]
