# Generated by Django 5.0.1 on 2024-01-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_job_finder', '0004_excludeword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedword1level',
            options={'verbose_name': '#1 Ключевое слово 1 уровня', 'verbose_name_plural': '#1 Ключевые слова 1 уровня'},
        ),
        migrations.AlterModelOptions(
            name='allowedword2level',
            options={'verbose_name': '#2 Ключевое слово 2 уровня', 'verbose_name_plural': '#2 Ключевые слова 2 уровня'},
        ),
        migrations.AlterModelOptions(
            name='disallowedword',
            options={'verbose_name': '#3 Запрещенное слово', 'verbose_name_plural': '#3 Запрещенные слова'},
        ),
        migrations.AlterModelOptions(
            name='excludeword',
            options={'verbose_name': '#4 Слово для исключения', 'verbose_name_plural': '#4 Слова для исключения'},
        ),
    ]
